services:
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      
  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend